default: &default
  adapter: postgresql
  encoding: utf8
  database: <%= Settings.db.primary.name %>
  username: <%= Settings.db.primary.user %>
  password: <%= Settings.db.primary.password %>
  host: <%= Settings.db.primary.host %>
  port: <%= Settings.db.primary.port %>
  pool: 35

development:
  <<: *default

test:
  <<: *default
  database: modular_monolith_test

staging:
  <<: *default

production:
  <<: *default
